### PR TITLE
Fixed invalid password issue

### LINKED ISSUE #52: When signing up, passwords under 6 characters are allowed
After entering password and clicking "Sign Up," an error message should appear if the password is less than 6 characters and the user should be prevented from moving to the Create Username page. 

Passwords under 6 characters will cause Supabase's signUp method to return a null session.

### PR DESCRIPTION
**Pull request by kaceyna**
#52

### CODE REVIEW

File: components/auth.tsx [hunk 1]
```diff
@@ -125,4 +145,10 @@ const getStyles = (theme: Theme) =>
       padding: 10,
       minWidth: "80%",
     },
+    errorMessage: {
+      textAlign: "center",
+      color: theme.error,
+      fontSize: 14,
+      marginBottom: "10%",
```
Comment (notforrest) [inline components/auth.tsx]: The textbox margins don't seem consistent.

image

**Review by notforrest — CHANGES_REQUESTED** [review]

File: components/auth.tsx (hunk 1 above)
Comment (kaceyna) [reply components/auth.tsx]: Fixed

**Review by notforrest — APPROVED** [review]
