### PR TITLE
Bug fix for items disappearing when toggling edit or delete in MyPantry

### LINKED ISSUE #20: Items disappear when toggling Trash and Edit buttons
Text disappears and UI bugs out after toggling the trash or edit buttons after collapsing and expanding the category once.

**To Reproduce:**
1. Add any number of ingredients to the pantry.
2. Collapse the category with ingredients in it.
3. Expand that same category.
4. Toggle the trash button or edit button.
5. Text formatting disappears.

### PR DESCRIPTION
**Pull request by eddwang**
#20 

Future changes:

- Swipe to edit or delete

### CODE REVIEW

File: components/whats-new-modal.tsx [hunk 1]
```diff
@@ -59,4 +59,4 @@ const getOnboardingStyles = (_theme: Theme) =>
       marginBottom: 10,
       textAlign: "center",
     },
-  });
+  });
```
Comment (notforrest) [inline components/whats-new-modal.tsx]: Keep the newline for linting

Comment (eddwang) [reply components/whats-new-modal.tsx]: fixed

**Review by notforrest — APPROVED** [review]
